Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EF.Models;
namespace EF.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        DataClasses1DataContext da = new DataClasses1DataContext();
        public List<Product>ls(int count)
        {
            return da.Products.OrderByDescending(a => a.Productname).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var t = ls(5);
            return View(t);
        }
        public ActionResult chude()
        {
            List<Product> ds = da.Products.ToList();
            return PartialView(ds);
        }
        public ActionResult detail(int id)
        {
            Product s = da.Products.FirstOrDefault(t => t.Id == id);
            return View(s);
        }   
        public ActionResult hienthitheocd(int id)
        {
            List<Product> p = da.Products.Where(t => t.Id == id).ToList();
            return View("Index",p);
        }
    }
}

Views/Demo/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@using EF.Models;
@model IEnumerable<Product>
<div class="container">
    <div class="row">
        @foreach (Product s in Model)
        {

            <div class="col-lg-3 card mr-2 mt-2 text-center">
                <div class="card-product">
                    <img src="~/Content/book/@s.Image" alt="Alternate Text" style="width:300px; height:350px;" />
                    @s.Productname
                    <div class="card-body">
                        <button class="btn-dark">Chọn sách</button>
                        @Html.ActionLink("chi tiết sách", "detail", "Demo", new { id = @s.Id }, new { @class = "btn btn-warning" })

                    </div>
                </div>

            </div>
      
    }
    </div>
    </div>

Views/Demo/chude.cshtml
@using EF.Models
@model List<Product>
<ul class="nav flex-column">
    @foreach(var s in Model)
    {
        <li class="nav-item border">@Html.ActionLink(@s.Productname, "hienthitheocd", "Demo",new { id=@s.Id},new { @class="nav-link"})</li>
    }
</ul>

Views/Demo/detail.cshtml
@{
    ViewBag.Title = "detail";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@using EF.Models;
@model Product
<h2>Thông tin chi tiết 1 cuốn sách</h2>
<div class="row">
    <div class="col-md-4">
        <img src="~/Content/book/@Model.Image" style="height:300px; width:auto" alt="Alternate Text" />
        <p>@Model.Productname</p>
        <p>Giá: @Model.Price</p>
    </div>
</div>